# Site settings
title:       Kasun Gamlath
email:       kasun.gamlath.x@gmail.com
author:      Kasun Gamlath
description: "Undergraduate."
baseurl:     ""
url:         "https://kasungamlath.com"

# Google analytics
google_analytics: UA-50840575-2

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: kasungamlathswebsite

# Social icons
show_social_icons: true
github_username: kpgx
stackoverflow_id:
twitter_username: kasungamlath
google_plus_id:
linkedin_username: kasungamlath
facebook_username: kpgxyz
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
